### ISSUE TITLE
请问出现如下错误是什么原因

### ISSUE THREAD

**Issue by yandt** [wgzhao/dbeaver-agent#1]
Caused by: java.lang.ClassNotFoundException: dev.misakacloud.dbee.interceptor.LoadKeyInterceptor cannot be found by com.dbeaver.model.license_2.0.154.202404011634
        at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

**Comment by wgzhao** [comment]
请提供具体的版本，在命令行运行的完整输出
