### ISSUE TITLE
java.lang.ClassNotFoundException: dev.misakacloud.dbee.interceptor.LoadKeyInterceptor

### ISSUE THREAD

**Issue by wingyuenlabs** [wgzhao/dbeaver-agent#2]
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
===============DBeaver-EE Agent===============
开始进行类替换
准备劫持解密密钥获取
解密密钥获取已经劫持
劫持证书检查
准备修改验证结果
验证返回结果修改完成,启动程序

java.lang.NoClassDefFoundError: dev/misakacloud/dbee/interceptor/LoadKeyInterceptor
	at com.dbeaver.model.license.embedded.LicenseKeyProviderEmbedded.getDecryptionKey(LicenseKeyProviderEmbedded.java)
	at com.dbeaver.lm.api.LMLicenseManager.importLicense(LMLicenseManager.java:156)
	at com.dbeaver.model.license.embedded.LicenseServiceEmbedded.importProductLicense(LicenseServiceEmbedded.java:120)
	at com.dbeaver.ui.license.LicenseImportDialog.importLicenseFromText(LicenseImportDialog.java:159)
	at com.dbeaver.ui.license.LicenseImportDialog.buttonPressed(LicenseImportDialog.java:255)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:265)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1630)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1392)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4427)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4003)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.dbeaver.ui.license.LicenseManagerUIUtils.importLicense(LicenseManagerUIUtils.java:153)
	at com.dbeaver.ui.license.LicenseManagerUIUtils.importMissingLicenseInUI(LicenseManagerUIUtils.java:117)
	at com.dbeaver.ui.license.LicenseManagerUIUtils.lambda$0(LicenseManagerUIUtils.java:83)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4382)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4005)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.eula.EULAUtils.showEulaConfirmationDialog(EULAUtils.java:68)
	at org.jkiss.dbeaver.ui.eula.EULAUtils.showEula(EULAUtils.java:60)
	at org.jkiss.dbeaver.ui.eula.EULAInitializer.initializeWorkbenchWindow(EULAInitializer.java:34)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchWindowAdvisor.lambda$2(ApplicationWorkbenchWindowAdvisor.java:357)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4382)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4005)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	at com.dbeaver.application.DBeaverApplicationAdvanced.start(DBeaverApplicationAdvanced.java:97)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
Caused by: java.lang.ClassNotFoundException: dev.misakacloud.dbee.interceptor.LoadKeyInterceptor cannot be found by com.dbeaver.model.license_2.0.166.202409091031
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 59 more
2024-09-29 13:29:11.514 - Event loop exception
java.lang.NoClassDefFoundError: dev/misakacloud/dbee/interceptor/LoadKeyInterceptor
	at com.dbeaver.model.license.embedded.LicenseKeyProviderEmbedded.getDecryptionKey(LicenseKeyProviderEmbedded.java)
	at com.dbeaver.lm.api.LMLicenseManager.importLicense(LMLicenseManager.java:156)
	at com.dbeaver.model.license.embedded.LicenseServiceEmbedded.importProductLicense(LicenseServiceEmbedded.java:120)
	at com.dbeaver.ui.license.LicenseImportDialog.importLicenseFromText(LicenseImportDialog.java:159)
	at com.dbeaver.ui.license.LicenseImportDialog.buttonPressed(LicenseImportDialog.java:255)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:265)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1630)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1392)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4427)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4003)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.dbeaver.ui.license.LicenseManagerUIUtils.importLicense(LicenseManagerUIUtils.java:153)
	at com.dbeaver.ui.license.LicenseManagerUIUtils.importMissingLicenseInUI(LicenseManagerUIUtils.java:117)
	at com.dbeaver.ui.license.LicenseManagerUIUtils.lambda$0(LicenseManagerUIUtils.java:83)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4382)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4005)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.eula.EULAUtils.showEulaConfirmationDialog(EULAUtils.java:68)
	at org.jkiss.dbeaver.ui.eula.EULAUtils.showEula(EULAUtils.java:60)
	at org.jkiss.dbeaver.ui.eula.EULAInitializer.initializeWorkbenchWindow(EULAInitializer.java:34)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchWindowAdvisor.lambda$2(ApplicationWorkbenchWindowAdvisor.java:357)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4382)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4005)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	at com.dbeaver.application.DBeaverApplicationAdvanced.start(DBeaverApplicationAdvanced.java:97)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
Caused by: java.lang.ClassNotFoundException: dev.misakacloud.dbee.interceptor.LoadKeyInterceptor cannot be found by com.dbeaver.model.license_2.0.166.202409091031
	... 59 more

**Comment by GlynisJ** [comment]
试试这个方法 https://github.com/Jacksx20/DBUltimate_Cracking

**Comment by drxaos** [comment]
fixed by adding to ini file `-Xbootclasspath/a:<path to agent library>`
