### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/dbeaver/lm/api/LMProduct

### ISSUE THREAD

**Issue by vseries** [wgzhao/dbeaver-agent#5]
win11系统 Java 17，报错

Exception in thread "main" java.lang.NoClassDefFoundError: com/dbeaver/lm/api/LMProduct
        at dev.misakacloud.dbee.License.genLicense(License.java:41)
        at dev.misakacloud.dbee.License.call(License.java:90)
        at dev.misakacloud.dbee.License.call(License.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at dev.misakacloud.dbee.License.main(License.java:82)
Caused by: java.lang.ClassNotFoundException: com.dbeaver.lm.api.LMProduct
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 12 more

**Comment by wgzhao** [comment]
1. 运行的 DBeaver 是什么版本？
2. 内置的 JRE 是否已经替换？
3. 运行的是哪种操作系统，版本是什么？
4. 在命令行启动 dbeaver，然后再输入许可，贴出命令行的完整输出内容
